### ISSUE TITLE
유니티 에디터 창 에러 내용 문의 드립니다. 

### ISSUE THREAD

**Issue by mhkim0720** [naverz/zepeto-script-sample#100]
아래 이미지 처럼 워닝이 계속 많아 지는데 ZepetoBaseModel.prefab 과 관련 된거 같은데 해결 방법이 있을까요? 
개발환경 : 윈도우 10/ 유니티 프로 입니다. 

![image](https://user-images.githubusercontent.com/8485731/143514963-24cbff53-924e-43a9-a276-4383e07e6547.png)

**Comment by x4cf** [comment]
실행에는 문제없지만 확인불가능한 에러코드는 맥과 윈도우 모두 발생하고있는 현상입니다. 개발자는 해결할 수 없는 것으로 보이니 일단은 못본척하는게 좋아보입니다 :D
