### ISSUE TITLE
윈도우에서 스크립트 적용이 잘안되는 문제 해결 법으로 

### ISSUE THREAD

**Issue by mhkim0720** [naverz/zepeto-script-sample#101]
1.0,4 버전으로 바꿧는데 클라이언트 쪽 적용은 전보다는 잘되는거 같은데 서버쪽 index.ts 파일 수정했을때 적용이 전혀 안됩니다. 
모두 리빌드올 해봐도 전혀 안되고.  Inspector - Importer - Zepeto.Multiplay.Script.Editor.ZepetoMultiplayerResourceImporter 
를 -> Zepeto.Multiplay.Script.Typescript.AssetImporter 로 변경하면 
스키마 Player 객체가 함수를 참조 못하면서 에러가 엄청 많아 집니다. 

예를 들어 Player.get / set 같은 경우에 get/set 함수를 참조를 못한다고 나오는 등의 참조 오류가 발생합니다. 

해결 방법에 아시면 답변 부탁합니다.

**Comment by x4cf** [comment]
코드 스크린샷을 한번 볼 수있으면 파악하는데 더 좋을것 같아요 :)

**Comment by NoahHahm** [comment]
SchemaTypes/index.d.ts 파일이 원래는 ZepetoMultiplayResourceImporter 를 참고해야하는데
TypescriptAssetImporter 를 참고하는 문제가 있는것을 확인했습니다.

**Comment by NoahHahm** [comment]
Importer 는 수정하시면 안됩니다. (에러의 원인)
multiplay 폴더내 ts 파일은 ZepetoMultiplayerResourceImporter 를 가져야하고,
예외적으로 SchemaTypes 내부에 있는 파일은 TypescriptAssetImporter 를 가져야 합니다.
에러가 재현되는 간단한 샘플프로젝트를 첨부해주시면 더 도움이 될듯 합니다.

**Comment by NoahHahm** [comment]
![image](https://user-images.githubusercontent.com/6405162/143668932-57ba8652-535a-4db4-9aa7-21f5a3c4ff50.png)

이런 부분들이 빨간색으로 에러가 표시되고 있으신건가요?

**Comment by mhkim0720** [comment]
에러는 importer 를 바꾸면 발생하는거라 다시 되돌리면 괜찬고 문제는 1.0.4 버전에서 index.ts 를 수정하면 반영이 안되어 애니메이션 싱크나 다른 기능 구현이 힘든 상황이네요 제가 구현하려는게 빌드잇으로 만든 맵처럼 수영장에서 수영하고 의자에 앉고 하는 기능이에요

**Comment by mhkim0720** [comment]
자답입니다 vs 코드 디버그 출력 쪽에 local ts / multi ts 로그가 따로 찍히는 거였네요 로그가 안찍혀서 동작안한다고 봤는데 로그 따로 잘 출력됩니다 유니티 에디터 로그는 클라이언트 로그만 찍히네요
