### ISSUE TITLE
서버 데이터전달 관련 질문

### ISSUE THREAD

**Issue by xowjd913** [naverz/zepeto-script-sample#102]
안녕하세요 서버코드에서 클라이언트로 메시지를 전달할때
클래스에 데이터를 채워서 전달할방법은없나요?

혹시 서버코드에서 Json 으로 파싱해서 스트링한개를 던져야할까요?

**Comment by crash-kim** [comment]
안녕하세요.
객체를 전달하는 방식은 현재 준비중이고 다음 버전에 배포 예정입니다.(12월 예정)
현재는 객체를 전달하려면 말씀하신 것처럼 객체를 json으로 직렬화해서 string으로 전달하시는 방식으로 사용 할 수 있습니다.

**Comment by xowjd913** [comment]
> 안녕하세요. 객체를 전달하는 방식은 현재 준비중이고 다음 버전에 배포 예정입니다.(12월 예정) 현재는 객체를 전달하려면 말씀하신 것처럼 객체를 json으로 직렬화해서 string으로 전달하시는 방식으로 사용 할 수 있습니다.

빠른답변 감사합니다.
혹시 클라이언트 쪽에서 받았을때 Json데이터를 클래스로 파싱해서 쓸수있는 방법은 있나요 ?
현재 서버쪽에서 Json데이터 던지는 부분은 확인했습니다.

![image](https://user-images.githubusercontent.com/25768804/143971759-adc2e8f1-c9f6-4208-860f-6afaf38021bd.png)


![image](https://user-images.githubusercontent.com/25768804/143971809-54aaa652-6b58-47ad-83b5-8d870a0fe802.png)

**Comment by xowjd913** [comment]
> 

자문 자답입니다. Typescript의 기본적인 지식은 충분히 있어야 겠네요 ㅠㅠ ...

![image](https://user-images.githubusercontent.com/25768804/143976000-b09ee2c8-ad5a-4163-8524-fec85594e9d8.png)

![image](https://user-images.githubusercontent.com/25768804/143976020-2c4ed129-e816-48b7-b33e-3cc8a723a594.png)
