### ISSUE TITLE
리더보드기능 업데이트 된건가요?

### ISSUE THREAD

**Issue by x4cf** [naverz/zepeto-script-sample#103]
리더보드 클래스가 보이네요

**Comment by cheolhui-lee** [comment]
안녕하세요.
사실은 리더보드 기능이 오픈 시점부터 제공되고 있었습니다.
다만 아직 사용성이 좀 불편하여 문서 오픈을 하지 않은 상태입니다.
현재 편의성을 높이는 작업을 진행하고 있고, 아마 다음 제페토 업데이트에 맞춰서 문서 공개를 할 수 있도록 준비하고 있습니다.
조금만 기다려 주시면 리더보드를 활용하여 멋진 컨텐츠를 제작하실 수 있을 것 같습니다.
고맙습니다.
