### ISSUE TITLE
Leaderboard 관련 질문이 있습니다

### ISSUE THREAD

**Issue by citytexi** [naverz/zepeto-script-sample#104]
World.multiplay 내부에 있는 index.d.ts파일에 Leaderboard가 있는데
해당 기능을 사용하는 가이드가 있을까요?
기능 구현이 안 된 상태라면 따로 구현을 해야하는건가요?

**Comment by x4cf** [comment]
#103 답변 참고하시면 좋을듯 합니다

**Comment by hyeonjin-jo** [comment]
안녕하세요

위에 댓글 남겨주신 것 처럼 https://github.com/naverz/zepeto-script-sample/issues/103 답변 참고 부탁드립니다
