### ISSUE TITLE
빌드는 성공하지만 컴퓨터와 달리 모바일에서 기능들이 작동하지 않습니다.

### ISSUE THREAD

**Issue by MuKyoung** [naverz/zepeto-script-sample#106]
모두 ts스크립트로 작성했으며 오류도 없습니다. 
컴퓨터에서는 모두 정상작동합니다.
그러나 모바일에서는 qr코드를 통한 월드 접속은 되지만 주요기능들이 전혀 작동하지 않습니다.
혹시나 해서 사용하는 ts스크립트들을 모두 Force Rebuild도 해보았는데 같은 결과입니다.
뭔가 세팅을 잘못했는지 아무리 확인해봐도 잘 모르겠네요 ㅠㅠ
지금 같은 상태에서는 아무리 개발을 해도 의미가 없어서 해결방법을 꼭 알려주시면 좋겠습니다,,,,

**Comment by crash-kim** [comment]
안녕하세요.
혹시 어떻게 동작을 안하는지 좀 더 자세히 알 수 있을까요?
스크린샷이나 동작하지 않는 코드를 추가해주시면 확인해보는데 도움이 될 것 같습니다.
추가로 운영체제와 제페토 버전도 같이 공유해 주시면 좋을 듯 합니다.

**Comment by MuKyoung** [comment]
![제페토1](https://user-images.githubusercontent.com/75478318/144166449-09377816-034c-4b9f-a2e4-cd7eaa55cb40.PNG)

![제페토2](https://user-images.githubusercontent.com/75478318/144166451-48b259e8-cdba-4cfd-9866-afaae0b90d67.PNG)

![제페토3](https://user-images.githubusercontent.com/75478318/144166454-941e03e4-78a3-402c-ba0d-57cf48539b46.PNG)

윈도우10 사용중이며 제페토 버전은 3.7.6입니다.

qr 코드 인식을 통한 모바일 접속까지는 가능합니다. 
그러나 모바일에서 위 스크립트들의 기능이 전혀 동작하지 않습니다.
빌드 후 플레이 시 컴퓨터에서는 동작이 되는 스크립트들입니다.
저도 더 자세히 말씀드리고 싶은데 오류도 안뜨기 때문에 어떤 부분이 문제인지 잘 모르겠네요....
아래의 스크립트 코드는 빌드 후 모바일과 컴퓨터에서 모두 동작 됩니다.
![제페토4](https://user-images.githubusercontent.com/75478318/144167406-4876cecb-3a9d-4fce-bdc2-6dafc772268e.PNG)

**Comment by hyeonjin-jo** [comment]
안녕하세요

현재 태그관련 기능에 문제를 발견해서 다음 버전에서 수정 예정입니다

제페토앱 3.8.0 이상부터는 적용되도록 조치하겠습니다

감사합니다
