### ISSUE TITLE
테스트 접속 링크를 통한 테스트가 불가능합니다

### ISSUE THREAD

**Issue by x4cf** [naverz/zepeto-script-sample#107]
큐알코드나 에디터 테스트로는 문제없이 실행되는 프로젝트가 패키지를 만들어서 "테스트 접속 링크"를 통한 테스트에서는 서버에 접속이 되지 않습니다.

**Comment by x4cf** [comment]
접속 자체는 되는대 캐릭터가 생성되지 않습니다.

**Comment by x4cf** [comment]
마치 에디터에서 서버를 끄고 플레이를 누른것과 같은 화면이 됩니다.

**Comment by cheolhui-lee** [comment]
안녕하세요.
어제 배포했던 멀티플레이 서버에 이슈가 있어서 현재는 긴급 롤백을 해둔 상태입니다.
조금 전 (대략 14시 경) 롤백을 했고 현재 접속이 정상적으로 되는 것으로 보이는데,
지금 다시 확인 부탁드려도 될까요?

**Comment by x4cf** [comment]
네 정상작동합니다! 정말 감사합니다!!!!
