### ISSUE TITLE
로그인한 캐릭터로 캐릭터가 생성되지 않는 문제... 오류 장면이나 오류 코드라도 보고싶습니다. 어떻게 해결해야할까요...

### ISSUE THREAD

**Issue by x4cf** [naverz/zepeto-script-sample#108]
예제를 참고하여 프로젝트를 만들어 QR코드, 에디터, 테스트 접속 링크와 테스터 등록을 통한 테스트, IOS, 안드로이드, M1맥 모두 정상적으로 진행되지만 심사에서는 캐릭터가 정상적으로 생성되지 않는것으로 보입니다.

테스트 접속 링크를 통한 테스트 장면입니다

![KakaoTalk_Photo_2021-12-01-22-02-17 001](https://user-images.githubusercontent.com/90679926/144239187-c9837325-0edc-43e9-bc47-98cf124200e3.jpeg)

![KakaoTalk_Photo_2021-12-01-22-01-57](https://user-images.githubusercontent.com/90679926/144239194-f9695513-1c11-43bd-83dc-69f64bad113e.jpeg)

![KakaoTalk_Photo_2021-12-01-22-02-17 002](https://user-images.githubusercontent.com/90679926/144239209-3bd9f241-e0fc-4c95-a54b-13c7e7060e00.jpeg)

예제의 클라이언트 스타터를 그대로 사용중이며 어떻게 해결해야할지, 오류가 나오는 장면을 볼 수 조차 없는 상황입니다.
혹시 조금만 해답을 얻을 수 있을까요...

<img width="788" alt="스크린샷 2021-12-01 오후 10 03 53" src="https://user-images.githubusercontent.com/90679926/144239342-0de8eec7-d92c-4e88-b172-de6d150f9bba.png">

**Comment by NoahHahm** [comment]
내부에서 의심되는 문제에 대한 사항을 확인했습니다.
앱 자체를 패치해야 하는 상황이긴해서 우선 해당부분은 내부에서 고려하여 등록할수있는 방안을 이야기 중입니다.
조금만 기다려주세요.

**Comment by x4cf** [comment]
저는 12월 1일에 캐릭터 생성문제로 월드가 심사거절되었는데 11월 26일에 심사통과된 월드가 보입니다... 오늘도 새로운 월드가 올라와서 저도 월드를 제출하기는 했습니다.
지금은 문제가 해결되어 월드 제출이 가능할까요?
11월에 심사 통과는 어떻게 가능했던건가요?
