### ISSUE TITLE
 ZEPETO 템플릿 등록 오류

### ISSUE THREAD

**Issue by HAENGIN** [naverz/zepeto-script-sample#11]
1.파일 다운로드 시점: 2021.10.18. 오전 00시20분

2.unity hub 버전: 2.4.5 윈도우 버전: windows 10

3.import 방식: Unity 메뉴에서 Assets → Import Package → Custom Package 를 차례로 클릭후 ZEPETO.World.unitypackage 파일 import클릭

4.자세한 설명: 제페토 스튜디오 가이드에 나와있는 유니티 설치 및 제페토 템플릿 등록하기 과정을 똑같이 따라하는 과정중 제페토 월드 패키지 파일을 import 하려 했지만 앞서 말했듯이 에러 문구와 함께 comlpete란 문구가 뜨지않고 진행되지않습니다 
사진도 함께 첨부하고싶은데 첨부를 할 수가없네요
똑같은 문의 메일로 답변 보내드렸는데 답장이없어 여기에도 질문드립니다.

**Comment by hyeonjin-jo** [comment]
추가 댓글이 없고 재현이 되지않아서 이슈 클로즈 하겠습니다

혹시 재현이 된다면 리오픈 부탁드립니다
