### ISSUE TITLE
1.0.6 업데이트 후 Create Custom Environment 로 접속하던게 

### ISSUE THREAD

**Issue by mhkim0720** [naverz/zepeto-script-sample#113]
안되네요 피시 두대로 테스트 하던 건데 업데이트 후 발생한 문제가 맞나요? 

업데이트 전에 테스트 환경은 서버 역할 피시 를 Development 로 놓고 
클라이언트 역할 피시에서 Custom environment 로 아이피 , 18080 으로 접속해서 테스트 했었습니다. 

답변 부탁합니다. ~

**Comment by hyeonjin-jo** [comment]
안녕하세요

현재 포트관련 이슈를 발견하여 수정되었습니다 다음 World Package 버전에서 적용될 예정입니다

최대한 빠른 시기에 적용하도록 하겠습니다

감사합니다

**Comment by mhkim0720** [comment]
안녕하세요 
그럼 다음 1.0.6 버전 다음 버전 전에는 멀티 기기 테스트를 사용 못하는 걸까요??? 
멀티 환경 디버깅이 급하게 필요한 상황인데 난감하네요 !! 우회 방법같은건 없나요?

**Comment by hyeonjin-jo** [comment]
https://github.com/naverz/zepeto-studio-kor/discussions/44

위의 답변 확인 부탁드리고  추가로 포트의 경우 아래의 이미지처럼 제페토 버튼을 눌러서 QR을 만들어보시면 아래에 ip와 포트가 나오게됩니다.

![스크린샷 2021-12-10 오후 4 40 38](https://user-images.githubusercontent.com/92719846/145536165-c4877361-d9d9-4d63-b022-11e6e4308470.png)
