### ISSUE TITLE
공식맵에 있는 모든 UI를 커스텀 유니티 월드에서 사용할 수 있나요?

### ISSUE THREAD

**Issue by sgexclsv** [naverz/zepeto-script-sample#114]
안녕하세요.
유니티 기반의 월드 UI 관련하여 질문이 있습니다.

현재 예제와 가이드를 통해 확인할 수 있는 룸 생성시 기본 제공되는 UI는 다음과 같습니다.
1. 방 참여자 목록
2. 나가기
3. 메시지창

그런데 제페토 공식맵에서는 더 많은 UI와 기능을 제공하고 있습니다.
1. 화면 가로 세로 전환 버튼
2. 음성 채팅 버튼
3. 가방 버튼
4 제스처/포즈 버튼
5. 촬영 버튼
6. 점프 버튼 주위 숏컷 버튼
7. 설정 버튼
8. 월드 퀘스트
9. 상점
10. 도감
등이 그것입니다.

현재 가이드 문서나 깃허브 이슈 등에서는 이 부분에 대한 구현 사항을 확인하기 어렵습니다.
이것들은 직접 구현해야 하는 것인지, 직접 구현이 가능한 것인지 알고 싶습니다. (예 : 상점으로 어떻게 접근하나요?)
혹은 이후에 이것들이 기본 제공되게끔 업데이트할 예정이신지 궁금합니다.

**Comment by crash-kim** [comment]
공식맵에 있느 UI는 현재 제공하고 있지 않습니다.
기본 제공 UI (홈버튼, 채팅)와 선택적으로 사용 가능한 v-pad UI 이외에는 유니티 UI 시스템을 활용해 직접 만들어야 합니다.
