### ISSUE TITLE
public으로 선언한 변수 사용

### ISSUE THREAD

**Issue by JungYerim** [naverz/zepeto-script-sample#116]
제페토 스크립트 파일을 여러개 만들어서 사용을 하고있는데,

public으로 선언한 변수가 해당 스트립트 파일이 아닌 다른 스크립트에서 참조가 되지 않습니다.
혹시 해결할 방법이 없을까요?

**Comment by crash-kim** [comment]
안녕하세요
혹시 참조하려는 스크립트가 참조하는 스크립트에 import 가 되어 있을까요?

**Comment by hyeonjin-jo** [comment]
안녕하세요

추가 문의가 없어서 이슈 종료합니다. 해당 이슈가 재발하거나 해결되지 않은 상황이라면 reopen 부탁드립니다.
