### ISSUE TITLE
Application.OpenURL 사용방법 (링크 접속방법)

### ISSUE THREAD

**Issue by JeongDongBaek** [naverz/zepeto-script-sample#118]
Application.OpenURL(this.url);
를 실행시 Exception: file:///C:/workspace/zepeto_thestylelist/Assets/LinkTest.js:12: Error: Exception of type 'ZEPETO.Script.Extensions.ForbiddenTypeExtension+ForbiddenException' was thrown.90427082b"}

Error: Exception of type 'ZEPETO.Script.Extensions.ForbiddenTypeExtension+ForbiddenException' was thrown.90427082b"}
오류구문이 뜹니다...

함수를 바로 사용이 안되는거같은데 어떻게 사용해야할까요?

**Comment by hyeonjin-jo** [comment]
안녕하세요.

현재 해당 함수는 정책적으로 막아 놓은 상태입니다.

참고 부타드립니다.
