### ISSUE TITLE
월드 만들기에 파일 등록시 에러

### ISSUE THREAD

**Issue by nice1378** [naverz/zepeto-script-sample#120]
패키지 파일을 등록할 때 시스템 업로드 실패가 뜹니다.

무엇이 문제인지 알 수 있는 방법이 있나요?

![KakaoTalk_20220111_151841735](https://user-images.githubusercontent.com/5405105/148894664-54ec8f9a-b40d-4c56-9962-185c58374c59.png)

**Comment by hyeonjin-jo** [comment]
안녕하세요

일시적인 서버 문제로 추측됩니다

현재는 재현이 되고있지 않아서 추가로 발견시 reopen 부탁드립니다

감사합니다
