### ISSUE TITLE
제페토 QR 테스트 접근 불가

### ISSUE THREAD

**Issue by Sunahram** [naverz/zepeto-script-sample#25]
안녕하세요 :) QR 테스트 관련해서 문의드립니다.

유니티에서 QR을 띄운 후 모바일로 실행하고자 했는데 되지 않고 있습니다.
아래 문의에서는 테스터 관련 문구가 뜬다고 하셨는데, 
제 경우 다음과 같은 문구가 뜨면서 접속이 되지 않습니다.
![image](https://user-images.githubusercontent.com/92986018/139452020-d16b2de1-0ed8-4daa-9744-c12d4d6c63d9.png)

1. pc와 모바일이 같은 인터넷을 사용하고 있고
2. 유니티에서 로그인, 월드 세팅을 마쳤으며,
3. 제페토 버전은 3.6.2 입니다.

어떻게 해결할 수 있을지 문의드립니다. 
그리고 테스터 설정은 어떻게 할 수 있는지 알려주시면 감사합니다 😊

**Comment by moondory77** [comment]
안녕하세요. 
우선 QR 코드를 통해 테스트 하는 부분은, 테스터 설정과는 무관한 부분입니다.
스크린샷으로 보여주신 화면은 
모바일 디바이스를 통해 제페토 월드 컨텐츠에 접속하는 과정에서 발생하는 '공통 오류 팝업'으로 원인을 단정짓기는 어렵습니다.
(네트웍 오류, 스크립트 오류 등..)

https://github.com/naverz/zepeto-multiplay-example의 멀티플레이를 포함한 예제를 제공드리오니, 해당 예제를 통해
먼저 기본적인 작동 사이클을 확인해보시는게 좋지 않을까 합니다.
