### ISSUE TITLE
특정 능력치를 올릴수있는 아이템은 어떻게제작해야할까요?

### ISSUE THREAD

**Issue by brilliantchoi** [naverz/zepeto-script-sample#27]
가이드에 보니 상품을 등록해서 유니티에 등록하는것 만나와있는데
특정 능력치를 한시적으로 올릴수있는 아이템을 제작/등록할 수 있나요?
(ex: 점프마스터-이동속도 5%증가 신발)

점프마스터에 있는 월드 게임내에서 구매할 수 있는 아이템같은 경우에는 어떻게 구현해야할까요?
캐릭터를 꾸미기 위한 아이템or이펙트만 등록가능한건가요?

**Comment by jason-snow** [comment]
아래의 가이드 참고 부탁드립니다. 

1. 아이템 (IWP) 가이드 
https://studio.zepeto.me/guides/in-world-purchases

2. 아이템 구매시 서버에서 캐릭터 상태 업데이트 예제
https://studio.zepeto.me/guides/handling-iwp-event(server)

3. 캐릭터 컨트롤러 가이드 (이동 속도 / 점프 능력치 조정용)
https://studio.zepeto.me/guides/character-control
