### ISSUE TITLE
제페토 에셋을 받을 수 있을까요?

### ISSUE THREAD

**Issue by JASONLEE-hub** [naverz/zepeto-script-sample#28]
게임 맵을 제작하는 데 있어 제페토에서 디자인 된 에셋을 사용 할 수 있을까요? 혹은 제공 해주는 에셋이 있을까요?

**Comment by hyeonjin-jo** [comment]
안녕하세요 
기존 빌드잇에서 사용하던 오브젝트를 제공할 예정입니다
업데이트되면 안내드리겠습니다

**Comment by x4cf** [comment]
<img width="1035" alt="스크린샷 2021-11-28 오전 9 47 40" src="https://user-images.githubusercontent.com/90679926/143724723-9088ce0f-d6bc-4f0c-8a51-16119c00d8b3.png">
빌드잇 모델이 추가되었습니다 :D
