### ISSUE TITLE
플레이 타임에서 제페토 닉네임을 on/off 하는 방법

### ISSUE THREAD

**Issue by Chelsea9900** [naverz/zepeto-script-sample#32]
제목 그대로입니다. 
게임을 플레이할 때, 상대방 아바타의 머리 위에 표시되는 
제페토 닉네임 텍스트를 숨기고 싶은데
어떤 방법으로 가능할지 여쭤보고싶습니다!

**Comment by cheolhui-lee** [comment]
안녕하세요.

현재는 해당 기능을 제공하지 않고 있지만,
의견 주신 대로 닉네임 표시 기능을 켜고 끌 수 있는 설정을 추가할 수 있도록 고민해 보겠습니다.

고맙습니다.
