### ISSUE TITLE
배경 요소 모델링 가이드 파일 공유가능 여부 질문

### ISSUE THREAD

**Issue by minjin5555** [naverz/zepeto-script-sample#33]
책상, 의자, 캐비닛 등 맵 배경 요소들도 상의, 하의, 신발 등과 같은 기본 모델링 가이드 파일을 받을 수 있을까요?

**Comment by minjin5555** [comment]
> 책상, 의자, 캐비닛 등 맵 배경 요소들도 상의, 하의, 신발 등과 같은 기본 모델링 가이드 파일을 받을 수 있을까요?

**Comment by hyeonjin-jo** [comment]
안녕하세요 
기존 빌드잇에서 사용하던 오브젝트를 제공할 예정입니다
업데이트되면 안내드리겠습니다

**Comment by hyeonjin-jo** [comment]
안녕하세요

배경 요소에 사용되는 모델링은 따로 가이드파일이 존재하지 않습니다
자유롭게 제작해서 사용가능합니다

추가로 빌드잇에서 기존에 사용하던 오브젝트를 제공할 예정이라서 참고부탁드립니다
