### ISSUE TITLE
특정 플레이어의 캐릭터 복사

### ISSUE THREAD

**Issue by diddntjd99** [naverz/zepeto-script-sample#34]
제목처럼 특정 플레이어의 캐릭터를 복사하여 npc와 같은 ai로 사용하려 하는데, 복사하는 방법에 대해 조언을 들을 수 있을까요?

**Comment by hyeonjin-jo** [comment]
안녕하세요
해당 기능은 특정 플레이어의 정보로 캐릭터를 생성하는 방식으로 제공 예정입니다
업데이트되면 안내드리겠습니다

**Comment by diddntjd99** [comment]
@hyeonjin-jo 
답변 감사합니다.
업데이트 일정은 언젠지 알 수 있을까요?

**Comment by cheolhui-lee** [comment]
정확한 날짜를 지정하기는 어려우나 12월 첫째 주에 업데이트 배포가 이루어질 것 같습니다.
고맙습니다.
