### ISSUE TITLE
제페토 앱 업데이트 관련

### ISSUE THREAD

**Issue by FOJF** [naverz/zepeto-script-sample#36]
제페토 앱을 업데이트했더니 테스트가 제대로 되지 않습니다!
업데이트 한 것이 문제인 것이 확실한지 궁금하여 이슈를 남기게 되었습니다.

아이폰 11 PRO MAX - ZEPETO 3.7.0 버전
아이폰 6S+ - ZEPETO 3.6.2 버전

위의 기기와 버전으로 테스트했을 때 최신버전인 ZEPETO에서는 제대로 캐릭터가 제대로 생성되지 않고 이전버전에서는 제대로 생성되었습니다.

**Comment by hyeonjin-jo** [comment]
안녕하세요 
world package 1.0.3 update 이슈로 인해 발생한 문제로 판단됩니다
최신 버전으로  push 후에 진행 부탁드립니다

**Comment by FOJF** [comment]
현재 제작중인 프로젝트에서는 불가능할까요?

**Comment by hyeonjin-jo** [comment]
별도의 프로젝트에서 진행 중이시라면 아래 이미지와 같이 Package Manager에서 ZEPETO.World 버전을 1.0.3으로 업데이트 진행 후에
(ZEPETO.World업데이트를 하면 다른 package들은 자동으로 업데이트진행됨)

![스크린샷 2021-11-03 오후 2 02 30](https://user-images.githubusercontent.com/92719846/140012055-e78ac070-f784-4560-baac-b0de5dc9c701.png)


Zepeto Players 컴포넌트에 None으로 되어있는 부분이 있다면 값을 채워야합니다.
EventSystem, Shadow 2개가 비어있는 경우가 발견되어서 EventSystem은 Scene에 배치되어있는 것으로 연결하고  Shadow는 Assets쪽에 CharacterShadow를 검색해서 연결해야합니다.

![스크린샷 2021-11-03 오후 1 53 03](https://user-images.githubusercontent.com/92719846/140011886-cb3a9503-8759-47ee-8ebe-4b3e873158be.png)

![스크린샷 2021-11-03 오후 1 58 36](https://user-images.githubusercontent.com/92719846/140012383-de4fe80d-5819-44af-b2da-204b93ab2369.png)

**Comment by FOJF** [comment]
답변해주신 그대로 ZEPETO.World를 업데이트했었는데 멀티플레이가 제대로 되지않습니다. 혹시 해결 방법이 있을까요?

MultiPlay Inspector
<img width="1792" alt="스크린샷 2021-11-03 오후 3 00 10" src="https://user-images.githubusercontent.com/61574220/140015679-0eef87d6-30ac-4da3-beeb-d79ddde3b60f.png">

ClientStarter Inspector
<img width="1792" alt="스크린샷 2021-11-03 오후 3 01 29" src="https://user-images.githubusercontent.com/61574220/140015754-7c96bd0c-ab4e-4afd-b4fe-d1e4d7b6f2e6.png">

**Comment by hyeonjin-jo** [comment]
Reimport All 버튼한번 눌러보시겠어요?

이후 ZepetoWorldMultiplay를 사용해야합니다.

![스크린샷 2021-11-03 오후 5 41 20](https://user-images.githubusercontent.com/92719846/140030522-48921a46-a2a1-448e-8836-72ad4bde107a.png)

**Comment by FOJF** [comment]
해결했습니다! 감사합니다!
