### ISSUE TITLE
미리 홍보해도 되나요?

### ISSUE THREAD

**Issue by x4cf** [naverz/zepeto-script-sample#37]
오픈채팅이나 네이버 카페를 개설해도 되나요?

**Comment by x4cf** [comment]
친구들이랑 즐기기에도 좋은것 같아보이는데

**Comment by cheolhui-lee** [comment]
안녕하세요.

홍보를 미리 하시는 것도 괜찮고, 오픈 채팅, 네이버 카페도 모두 괜찮습니다.
즐거운 콘텐츠를 만들어 주시고 주변 친구 분들과 함께 마음껏 즐겨주세요.

고맙습니다.
