### ISSUE TITLE
zepeto 패키지 설치 오류

### ISSUE THREAD

**Issue by zmnbnm** [naverz/zepeto-script-sample#38]
![image](https://user-images.githubusercontent.com/88330448/139849423-41429cad-365c-49b8-a037-1829f25884c6.png)

ExecutionEngineException: String conversion error: Illegal byte sequence encounted in the input.

재설치 후에 진행해도 동일한 현상 일어납니다.

폴더에 zepeto.world.template 파일은 생기나 해당 탬플릿으로 프로젝트 생성 시 에러로 생성 불가합니다.

**Comment by NoahHahm** [comment]
지금도 해당 이슈 재현되고 있으신걸까요?
사용하시는 OS 환경에 대한 정보도 같이 알려주실수 있을까요?

**Comment by hyeonjin-jo** [comment]
오랫동안 추가 대응이 없어서 우선 close 하겠습니다

동일한 증상이 반복된다면 reopen 또는 새롭게 이슈 등록 부탁드립니다.
