### ISSUE TITLE
여전히 모바일에서 월드 테스트가 되질 않습니다.

### ISSUE THREAD

**Issue by smartbh** [naverz/zepeto-script-sample#41]
유니티 엔진에서 제페토 빌드를 해서

qr코드로 찍고 들어가는 월드 테스트가 여전히 되질 않습니다

제페토 버전이 문제인가 싶어 업데이트 하여

최신 버전이고 

전에 말씀하셨던 같은 인터넷 환경에 있어야 한다 하셔서

컴퓨터 공유기 아이피와 같은 와이파이를 사용하여

같은 환경으로 조건도 맞추고 했는데도 제대로 되질 않습니다.

qr을 찍고 월드로 들어가보려고 하면

보라색 화면만 뜨면서 무한 로딩으로 되질 않습니다.

도저히 테스트를 할 수가 없는 환경인데 어떻게 해야할까요

**Comment by smartbh** [comment]
여러 기기, 와이파이 환경 전부 실험해 봤는데 안되는걸 보니

방화벽 설정 하는법을 알려주셔야 할것같습니다.

![image](https://user-images.githubusercontent.com/43138813/140637955-9587b44f-157c-4069-aa7c-0574b8b3a879.png)


pc 방화벽 설정 에선 제페토 앱을 찾기가 어렵습니다.

**Comment by moondory77-naverz** [comment]
안녕하세요.
넵 말씀주신대로, 윈도우 환경에서 모바일 디바이스를 통한 QR코드 접속 테스트가 
방화벽 설정으로 인해 원활하지 못한 경우가 있습니다. 

일반적으로, 테스트 하려는 (Unity)프로젝트에서 QR코드를 생성 시 방화벽 허용관련 팝업이 뜨지만
node.exe
Unity Editor 
에 대해, 방화벽이 허용되어 있는지 확인 부탁드립니다.

그럼에도 접속이 원활하지 않을 경우, 공용 방화벽을 잠시 끈 상태에서 확인을 부탁드리겠습니다.
![image](https://user-images.githubusercontent.com/93751484/140673229-616a1567-98d2-4ab8-a0fa-e36e6c6b3021.png)

**Comment by hyeonjin-jo** [comment]
추가 코멘트가 없어서 우선 Close 하겠습니다
문제가 있다면 리오픈 부탁드립니다

**Comment by smartbh** [comment]
유니티에서 qr코드 생성시 방화벽 앱 허용 리스트에 node.exe와 Unity Editor가 리스트에 보이질 않습니다

맨 처음 실행시켰을떄 허용 관련 팝업이 뜬적도 없구요

공용 방화벽까지 껐지만 여전히

보라색 화면에서 100%로딩 까지만 뜨고 월드로 넘어가지 않고있습니다.

![image](https://user-images.githubusercontent.com/43138813/142003963-7cadf3b8-ddf0-44c0-9374-421a4e233a47.png)
