### ISSUE TITLE
UI화면 씬 전환

### ISSUE THREAD

**Issue by jeejul1010** [naverz/zepeto-script-sample#42]
에디터에서는 씬 전환이 이루어지는데 모바일로 테스트시 메인화면에서 게임화면으로 씬 이동이 이루어지지 않습니다. 빌드 세팅에서 씬을 모두 추가했고 가이드에 나온대로 버튼 AddListener 콜백을 추가하여 버튼을 누르면 다음씬으로 넘어가게 구현했는데요(SceneManager.LoadScene(씬 이름)) 제페토 앱에서 씬전환을 확인하려면 어떻게 해야 하나요? 감사합니다

**Comment by hyeonjin-jo** [comment]
안녕하세요

씬 전환은 말씀해 주신 대로 빌드 세팅에 씬추가 이후에 SceneManager.LoadScene을 사용하면 됩니다.

모바일 환경에서도 정상 동작하는 것은 확인되었습니다.

다른 부분에서 발생하는 오류로 추측이 되어서 이 부분 확인 부탁드립니다.


*참고 코드
```typescript
import { ZepetoScriptBehaviour } from 'ZEPETO.Script'
import {SceneManager} from 'UnityEngine.SceneManagement'


export default class SceneChange extends ZepetoScriptBehaviour {

    Start() {
        SceneManager.LoadScene('testScene');
    }

}
```
