### ISSUE TITLE
ZEPETO.Character.Controller.Setting 접근 방법

### ISSUE THREAD

**Issue by Chelsea9900** [naverz/zepeto-script-sample#44]
안녕하세요! 
zepeto character controller 를 스크립트로 접근하는 방법이 있을까요?

(예) '특정 이벤트가 발생했을 때, 특정 캐릭터의 이동 속도를 높이는 기능' 을 구현하고 싶습니다

zepeto character controller에 관련된 대부분이 Read Only 로 되어있어 조언을 구하고 싶습니다

**Comment by moondory77-naverz** [comment]
안녕하세요.
스크립트를 통해, 제페토 캐릭터를 생성한 다음에는 
생성 시, 첫번째 파라메터로 넣은 sessionId를 통해 다음과 같이 ZepetoPlayer 컴포넌트에 접근 가능합니다.

ZepetoPlayers.instance.CreatePlayerWithUserId(sessionId, player.zepetoUserId, spawnInfo, isLocal);
...
const zepetoPlayer = ZepetoPlayers.instance.GetPlayer(sessionId);

(예)에서 말씀주신 '특정 캐릭터의 이동 속도를 높이는 기능'과 같은 경우,
위에서 접근한 zepetoPlayer객체를 통해

        zepetoPlayer.character.additionalRunSpeed += 1;
        zepetoPlayer.character.additionalJumpPower += 1;
        zepetoPlayer.character.additionalWalkSpeed += 1;

과 같은 방식으로 처리하실 수 있을 듯 합니다.
zepeto character에 대해, 스크립트를 통한 다양한 커스터마이징 옵션을 업데이트를 통해 추가드릴 수 있도록 하겠습니다.
