### ISSUE TITLE
파일 공유시 용량

### ISSUE THREAD

**Issue by FOJF** [naverz/zepeto-script-sample#46]
파일 공유시 불필요한 파일은 제외하고 공유하고 싶은데 빌드하거나 QR을 생성하면서 생성되는 것 같은 공유에 불필요한 파일을 알 수 있을까요?

**Comment by hyeonjin-jo** [comment]
안녕하세요
프로젝트 .gitignore 참고 부탁드립니다

https://github.com/naverz/zepeto-script-sample/blob/main/.gitignore
