### ISSUE TITLE
제페토NFT를 만들어도 되나요?

### ISSUE THREAD

**Issue by x4cf** [naverz/zepeto-script-sample#47]
https://medium.com/@RandomEarth/into-the-metaverse-a-zepeto-game-world-launching-on-random-earth-9d846d6ca41a

제페토 NFT가 있는것 같은데 저희도 만들어도 될까요?

**Comment by cheolhui-lee** [comment]
안녕하세요.

NFT 제작 관련해서는 상세한 질의 내용이나 제안이 있으실 경우 business@zepeto.me 로 별도 문의 부탁드립니다.

고맙습니다.
