### ISSUE TITLE
제페토 기본 그래픽 파일

### ISSUE THREAD

**Issue by Chelsea9900** [naverz/zepeto-script-sample#50]
안녕하세요!
혹시 제페토의 기본적인 그래픽 파일을 제공받을 수 있을까요??

(예) 레벨업이 되었을 때 뾰로롱 반짝이는 .png 파일 또는 .mp3 파일
(예) Respawn 되었을 때 캐릭터와 함께 나타나는 Effect Asset 파일

**Comment by cheolhui-lee** [comment]
안녕하세요.

아마도 이펙트 쪽을 필요로 하시는 것 같은데요.
기존 월드에서 사용되고 있는 그래픽 파일을 건 별로 분류해서 제공해드리기는 현실적인 어려움이 있습니다.
당장은 Unity Asset Store 등을 활용해 주시면 더욱 다양한 효과를 만나보실 수 있을 것 같습니다.

내부에서 제작된 각종 리소스를 제공해드리는 방식에 대해서는 다각도로 검토를 하고 있는 상황이지만,
정책적으로 고려해야 할 내용이 많이 있어서 시간이 많이 소요될 수 있는 점 양해 부탁드립니다.

고맙습니다.
