### ISSUE TITLE
제페토 타입스크립트 문제가 있습니다.

### ISSUE THREAD

**Issue by smartbh** [naverz/zepeto-script-sample#51]
막 개발을 시작한게 아닌

계속 엔진 내에서 개발 과정을 거치면서 

작업을 진행중이었고 잘 됐었습니다.

그런데 갑자기 어느 순간부터

타입스크립트 에러가 뜨더니

![image](https://user-images.githubusercontent.com/43138813/140637993-beb18573-6bc6-436d-822c-2169177a0d97.png)

![image](https://user-images.githubusercontent.com/43138813/140638052-4f86981f-ac83-4cf0-a392-2d1c0418e804.png)

이러한 오류로 실행 자체가 되질 않습니다.

스크립트 11번째  줄이라 확인 해봐도 큰 문제는 없습니다.

![image](https://user-images.githubusercontent.com/43138813/140637978-575c22e1-53a1-422d-8589-5a1392dbc717.png)

잘 되던게 타입스크립트 컴파일 관련 에러로 안되는데 어떻게 해야할까요?

지금까진 잘됐었습니다.

**Comment by NoahHahm** [comment]
/Library/node
node_modules

두 패스에 파일들이 정상적으로 위치되어 있는지 확인 가능할까요?

**Comment by smartbh** [comment]
> /Library/node node_modules
> 
> 두 패스에 파일들이 정상적으로 위치되어 있는지 확인 가능할까요? 혹은 ZEPETO - Experimental - Refresh Environments 버튼을 클릭하셔서 재시도 해봐주실수 있을까요?

둘다 확인해 봤는데 여전히 문제가 있습니다 ㅠㅠ

**Comment by hyeonjin-jo** [comment]
안녕하세요

프로젝트를 새로 만든 후 최신 World package로 업데이트 후 진행부탁드립니다

동일한 증상이 반복된다면 reopen 또는 새롭게 이슈 등록 부탁드립니다.
