### ISSUE TITLE
제페토 내의 API 사용이 가능하도록 업데이트 될 예정이 있을까요?

### ISSUE THREAD

**Issue by here0jang** [naverz/zepeto-script-sample#52]
제페토 캐릭터 꾸미기의 화장, 머리, 옷입기 API 를 사용해야 하는 게임을 기획했는데 
이 API 들의 사용이 가능하도록 업데이트 될 예정이 있는지 궁금합니다.

**Comment by here0jang** [comment]
> 제페토 캐릭터 꾸미기의 화장, 머리, 옷입기 API 를 사용해야 하는 게임을 기획했는데 이 API 들의 사용이 가능하도록 업데이트 될 예정이 있는지 궁금합니다.

**Comment by cheolhui-lee** [comment]
안녕하세요.
제페토에서 서비스되고 있는 의상, 화장 등의 아이템을 게임 내에서 바로 사용하실 수 있는 API는 제공되고 있지 않는데요.
파트너사와의 제휴 아이템이나 크리에이터가 제작한 다양한 아이템을 모두 제공하기는 어려울 수 있으나,
저희 회사 내부에서 제작한 아이템은 제공될 수 있는 방법을 다양하게 고민하고 있습니다.
하지만 개발 작업에 많은 시간이 걸릴 수 있는 상황이라서요.
우선은 로딩 된 캐릭터의 Game Object와 Component를 직접 제어하는 방식으로 개발 방법을 고민해 주시는 것이 좋을 것 같습니다.
고맙습니다.
