### ISSUE TITLE
Physics를 이용한 Layer Collision

### ISSUE THREAD

**Issue by FOJF** [naverz/zepeto-script-sample#54]
Project Settings > Physics > Layer Collision Matrix에서 충돌관리를 해주려고 했는데 PC환경에서는 제대로 작동하지만 모바일에서는 제대로 작동하지 않는 것 같습니다!

**Comment by cheolhui-lee** [comment]
안녕하세요.
Layer Collision Matrix 설정을 현재 제페토 패키지에 포함하고 있지 않아서 에디터는 해당 설정이 동작하더라도,
앱에서는 다른 설정인 상태라 정상 동작이 되지 않는 것으로 생각됩니다.

해당 설정을 포함할 수 있는 방법에 대한 내부 검토를 진행해보겠습니다.
