### ISSUE TITLE
외부 유료/무료 에셋을 사용하려고 하는데 텍스처나 에셋에 변화를 줘야 하나요? 

### ISSUE THREAD

**Issue by nelly0420** [naverz/zepeto-script-sample#55]
유니티 에셋 스토어에 있는 에셋을 사용해 월드를 구성해도 되는것인가요?
공모전 저작권 관련해서 에셋들을 그냥 가져오면 안된다는 말들이 있어서 여쭤봅니다~
기준이나 유의사항 있으면 알려주세요!

**Comment by hyeonjin-jo** [comment]
안녕하세요

에셋스토어에서 구매 후 사용하는 에셋들도 사용가능합니다.
저작권 관련은 해당 에셋 스토어에 등록된 문서를 확인 부탁드립니다.
