### ISSUE TITLE
Raycast(out hit) 을 사용할 수 없는 문제

### ISSUE THREAD

**Issue by Chelsea9900** [naverz/zepeto-script-sample#57]
기존의 Unity C# 문법은 out 키워드를 제공해주므로,
UnityEngine.Physics.Raycast() 가 
RaycastHit 타입의 구조체 데이터를 
매개변수로 받을 수 있는 걸로 알고있습니다

반면 타입스크립트는 C#과 달리 out 키워드가 제공이 안되어있어서 질문을 올립니다
이 문제를 어떻게 해결할 수 있을지 여쭤보고싶습니다

**Comment by hyeonjin-jo** [comment]
안녕하세요

아래 링크 참고 부탁드립니다
https://github.com/naverz/zepeto-script-sample/issues/30
