### ISSUE TITLE
DataStorage 기능 업데이트 되었나요?

### ISSUE THREAD

**Issue by x4cf** [naverz/zepeto-script-sample#59]
저장기능만 완성되면 얼추 즐길 수 있을것 같은데 저장기능 업데이트 되었나요?

**Comment by hyeonjin-jo** [comment]
안녕하세요
https://studio.zepeto.me/guides/multiplay-game-datastorage
위의 링크 참고 부탁드립니다

다만 ClientStorage쪽은 현재 수정중이어서 Server DataStorage만 우선 확인 부탁드립니다
