### ISSUE TITLE
제페토 3D 모델 사용 가능 여부

### ISSUE THREAD

**Issue by Chelsea9900** [naverz/zepeto-script-sample#61]
새로 업데이트 해주신 멀티플레이 예제 프로젝트를 보니 
교실을 배경으로 씬을 주셨더라구요.
혹시 여기에 있는 오브젝트들을 재사용해도 될까요??

(예) 1. 이 책상 모델을 저희가 제작 중인 씬에 넣어서 활용해도 될까요?
(예) 2. 이 책상 모델의 scale을 수정해서 활용해도 될까요?

<img width="452" alt="KakaoTalk_Photo_2021-11-11-16-35-59" src="https://user-images.githubusercontent.com/93331248/141257594-1112c0eb-6832-47b8-88da-77138b88a435.png">

**Comment by hyeonjin-jo** [comment]
안녕하세요
예제 프로젝트에서 제공하는 모든 리소스는 제페토월드 제작시 활용 가능합니다
