### ISSUE TITLE
제페토 스크립트의 NavMeshAgent 기능

### ISSUE THREAD

**Issue by diddntjd99** [naverz/zepeto-script-sample#63]
안녕하세요,
NavMeshAgent의 기능을 사용하여 ai를 제작하려 하는데,
제페토 스크립트에 NavMeshAgent가 구현이 되있을까요?

되있다면 유저의 캐릭터에 어떤식으로 접근해서 NavMeshAgent 컴포넌트를 달아야하는지 알고싶습니다!

**Comment by hyeonjin-jo** [comment]
안녕하세요
NavMeshAgent 기능을 제공하고 있고 아래와 같이 import 후 사용가능합니다
```typescript
import {NavMeshAgent} from 'UnityEngine.AI'
```

생성된 캐릭터에 추가 컴포넌트를 붙이는 방법은 아래 링크의 1번답변을 확인 부탁드립니다
https://github.com/naverz/zepeto-script-sample/issues/5
