### ISSUE TITLE
씬 전환 제페토 모바일 테스트시 하얀화면

### ISSUE THREAD

**Issue by jeejul1010** [naverz/zepeto-script-sample#64]
타이틀 씬 중간씬 게임씬을 만들었는데요 단순히 몇 초 후에 전환되게 만들었습니다. SceneManager.LoadScene을 사용했는데 에디터에서는 전환이 예상대로 이루어지는데 빌드세팅에 필요한 모든 씬을 추가하고 제페토 모바일 테스트를 하니 타이틀씬에서 중간씬으로 넘어갈 때 중간씬이 안뜨고 하얀화면이 뜨고 여기서 멈추게 됩니다. 게임씬으로 진입도 못하네요 ㅠㅠ왜 이러한 현상이 일어나는 걸까요?

**Comment by hyeonjin-jo** [comment]
안녕하세요 
씬전환은 SceneManager.LoadScene를 사용하는 방식이 맞습니다
현재 모바일환경에서도 정상동작하는 것을 확인해서 다른 코드나 세팅에 문제가 있는지 확인이 필요할 것 같습니다
