### ISSUE TITLE
제페토 캐릭터 애니메이션 수정 관련

### ISSUE THREAD

**Issue by Restnextsnak** [naverz/zepeto-script-sample#65]
제페토에서 제공하는 캐릭터의 애니메이션을 만들어서 넣거나 수정하려면 어떻게 해야하죠?

**Comment by moondory77-naverz** [comment]
안녕하세요. 
제페토 캐릭터 컨트롤러 모듈에서, 임의의 캐릭터 애니메이션 클립을 만들어 적용하는 방법은 다음과 같습니다.

1. Project 창에서 ZEPETO.Character.Controller/Runtime/_Resources/AnimatorController/ZepetoAnimator.controller 를 하여, 로컬 환경의 Assets/~ 경로로 드래그 이동합니다. (해당 에셋이 복사됩니다.)

<img width="533" alt="1 animator 에셋복사" src="https://user-images.githubusercontent.com/93751484/143047917-3545be42-1d76-4101-8dec-f2390350279e.png">
 
2. Hierachy 창의 ZepetoPlayers 오브젝트를 선택한 다음, Inspector 창의 [Player >> Animator Controller] 탭에 
복사해온 ZepetoAnimator.controller를 지정합니다.

<img width="597" alt="1 animator 커스텀지정" src="https://user-images.githubusercontent.com/93751484/143048520-ff59940f-e294-450a-b0c1-6609497380d9.png">

3. 해당 animation controller를 연 다음, state machine에 지정되어 있는 각각의 state에 대한 animation clip을 변경할 수 있습니다.
<img width="999" alt="3 커스텀clip지정" src="https://user-images.githubusercontent.com/93751484/143048847-4e86b470-48cb-4d90-8247-99eef74d9ba2.png">

**Comment by moondory77-naverz** [comment]
또한,
ZepetoAnimator.controller의 animation state machine에는, 
임의의 클립을 지정한다음, 필요할 때마다 해당 animation event를 invoke 할 수 있도록 
지정 state 슬롯을 제공하고 있습니다.

<img width="519" alt="3 Gesture_Custom" src="https://user-images.githubusercontent.com/93751484/143049305-aa7839a5-baed-41c1-aa7f-3016a4da8935.png">

스크립트에서 ZepetoCharacter 인스턴스에 대해,
임의의 animation clip을 다음과 같이 바로 Play/Stop 할 수 있습니다.

[Usage-ts]

 public character : ZepetoCharacter;
 public customClip:AnimationClip;        
...       
character.SetGesture(customClip);
character.CancelGesture();
...
