### ISSUE TITLE
제품제출할때 공모전 참가자인건 어떻게 알리나요?

### ISSUE THREAD

**Issue by x4cf** [naverz/zepeto-script-sample#66]
받은 몇개의 메일과 이 깃허브만 알고있는데, 다 만들면 어디에 메일을 보내야 한다거나 하는게 있나요?

**Comment by cheolhui-lee** [comment]
안녕하세요.
공모전 제출 관련해서는 아래와 같은 방식으로 진행해주시면 될 것 같습니다.

1. 제페토 스튜디오에 제품을 등록합니다.
2. 등록 후 다음 정보를 joohan@naverz-corp.com 으로 전달해주시면 됩니다.
   - 학교
   - 팀명
   - 인원명
   - 월드ID (World ID)
   - 월드 명

고맙습니다.
