### ISSUE TITLE
캐치마인드 형식의 게임을 만들게 되면서 정말 필요한 기능들이 있는데 사용이 가능할지 여쭤보고 싶습니다!

### ISSUE THREAD

**Issue by here0jang** [naverz/zepeto-script-sample#68]
안녕하세요! 저희는 주제나 키워드를 제페토 캐릭터 꾸미기로 표현해서 문제를 내고 맞추는 캐치마인드 형식의 게임을 기획했습니다.
이전에 현재로서는 API 사용이 힘들것 같다는 답변을 받았었는데 저희 게임이 진짜 제페토랑 어울리고 재미있는 게임이어서 너무 아쉬운 마음에 혹시 달라진 점이 있을지 궁금해서 여쭤보게 되었습니다.
첨부한 기획서 안에 상세한 플레이 방법을 올렸으니 읽어보시고 답변 주시면 감사하겠습니다!

[[제페토게임공모전기획] 팀E_제페토컨테스트_20211116_김주영 송채현 이지예 임세진 장혜령.pdf](https://github.com/naverz/zepeto-script-sample/files/7546391/E_._20211116_.pdf)

저희가 가진 질문은 2가지 입니다. 

1. 콜라보 아이템, 다른 크리에이터 아이템 등을 제외한 제페토 자체 제작 아이템들을 
 “저희 맵 내에서만” 플레이어들이 입거나 사용할 수 있는지 ( 맵 밖으로 나가면 적용했던 아이템들이 모두 사라짐)

2. 제페토 기본 꾸미기 API가 불러와 월드 내에서 꾸미기 화면과 즉시 연결이 가능한지
(첨부한 게임 플로우 사진 내에 캐릭터 꾸미기 기능이 불러와지는 지점을 표시하였습니다.)
<img width="7843" alt="제페토" src="https://user-images.githubusercontent.com/63058513/141975902-094e7c32-c61e-4174-8214-243a8147ceaf.png">

답변주시면 감사하겠습니다!

**Comment by cheolhui-lee** [comment]
안녕하세요.

1. 안타깝지만 현재로는 월드 콘텐츠에서 제페토의 아이템들을 조회하고, 캐릭터에 적용할 수 있는 방법을 따로 제공하고 있지 않습니다. 아이템들 중에는 크리에이터가 제작하거나 제휴 아이템들도 많아서 월드 콘텐츠에서 알맞게 이용할 수 있는 체계를 아직 갖추지 못했습니다. 내부적으로 계속 검토를 하고는 있으나 언제 된다고 확답 드리기는 어려운 상황입니다.

2. 기능적으로 제페토 본체와 월드는 완벽히(?) 분리되어 있다고 보시는 것이 좋을 것 같습니다. 월드 콘텐츠 내에서 제페토 본체의 기능을 호출하는 것은 현재로는 불가능합니다. 다만 1번과 연결하여 여러가지 방법을 검토를 해보겠습니다만, 일정을 확인 드리기는 어려울 것 같습니다.

고맙습니다.
