### ISSUE TITLE
OnTriggerEnter(Exit, Stay) 함수 사용시 충돌된 대상 Object의 정보를 얻을 수 있을까요?

### ISSUE THREAD

**Issue by thkim-nx3games** [naverz/zepeto-script-sample#70]
C#의 경우 void OnTriggerEnter(Collider other) 대상의 Collider 정보를 얻어서 활용한데요

**Comment by x4cf** [comment]
OnTriggerEnter(Collider){
   if(Collider.name == "player"){
   }
}
이런식으로 사용 가능합니다. 

코드 : Me793a2
https://open.kakao.com/o/gNaIjUKd
이곳에서 물어보시면 더 상세히 답변해드리겠습니다.
