### ISSUE TITLE
외부 라이브러리 참조 관련 문의

### ISSUE THREAD

**Issue by xowjd913** [naverz/zepeto-script-sample#71]
월드 제작시 외부 공유 라이브러리 (DLL / so) 를 사용 가능한가 문의드립니다.

현재 C++ 로 제작된 so 라이브러리를 사용 예정입니다.

**Comment by cheolhui-lee** [comment]
안녕하세요.
컴파일이 필요한, 또는 이미 컴파일이 된 라이브러리들은 사용이 불가능합니다.
이미 배포가 되어 있는 앱에는 해당 라이브러리들이 포함되어 있지 않기 때문인데요.

그렇기 때문에 런타임에서 실행이 가능한 **TypeScript**(JavaScript)만 실행이 가능합니다.
필요하신 기능들이 있다면 TypsScript로 포팅을 하고 프로젝트에 포함을 시켜주셔야 합니다.

고맙습니다.
