### ISSUE TITLE
캐릭터 애니메이션(Gesture)에 대한 사용법 요청드립니다.

### ISSUE THREAD

**Issue by thkim-nx3games** [naverz/zepeto-script-sample#72]
1. 예약된 제스츄에 대한 사용 방법
2. 자체적으로 개발된 AnimationClip을 활용하여 사용 방법

간단한 사용 방법 공유부탁드립니다.

**Comment by x4cf** [comment]
간단하게 설명하기 어려울것 같지만 
코드 : Me793a2
https://open.kakao.com/o/gNaIjUKd
이곳에서 질문드리면 시간될때 설명가능할것 같습니다.

**Comment by moondory77-naverz** [comment]
안녕하세요. #65 참고부탁드리겠습니다.
