### ISSUE TITLE
git 샘플소스 에러 관련 

### ISSUE THREAD

**Issue by mhkim0720** [naverz/zepeto-script-sample#75]
문의1) 
깃 데모 중에  CharacterControllerSample / MultiplaySample 을 제페토로 실행하면 

![image](https://user-images.githubusercontent.com/8485731/142566067-4b1a03ad-9b23-4928-9252-e4e2bbc2f6e9.png)

요런 에러가 나는데 해결 방법이 있을까요 ? 

문의2) 
다른 문의로 제페토 월드 버전을 1.0.3으로 패키지 매니저에서 설정하면 내부망으로 테스트가 안되는데 
1.0.2 로만 사용 가능 한 건가요? 

문의3) 
지금 구현 하려는게 빌드잇을 이용하지 않고 월드를 만든 다음에 그 월드에 수영장을 만들어서 플레이어 들이 수영칠 수 있게 
하고 싶은데 가능한 걸까요? 가능하다면 수영장 영역안에 플레이어가 들어 왔을때 
플레이어 애니메이션을 수영 애니메이션으로 바꿔주는 구현 방법에 대해 설명이 가능 할 까요? 
제페토가 아니라면 수영장 영역 내에 플레잉어가 들어 온것을 체크해서 그 영역 안에 있을때만 수영 애니메이션을 
하도록 작업하면 되는데 제페토에서는 어떤 식으로 구현 해야 되는지 궁금합니다. 

답변 부탁드립니다.

**Comment by x4cf** [comment]
오피셜개발자가 바뻐서 답변을 잘 안해줘서 저희끼리 도와야될것같습니다. 알고있는만큼 말씀드리자면 
1. 파일이 깨진것같습니다. 맥에서 윈도우로 파일 넘어갈때 자주 보이는 문구군요
2. 1.0.3으로 잘 작동합니다
3. 애니메이션을 자유롭게 만들 수 없거나 가이드 없이는 쉽지않아 보입니다. 재공하는 애니메이션 파일중에 선택해서 제작하는게 좋을것 같아보입니다.

**Comment by x4cf** [comment]
수정합니다.
3번 애니메이션 자유롭게 만들 수 있고 가이드 없이 어렵지 않게 변경이 가능합니다!
