### ISSUE TITLE
Resources.Load로 파일을 로드한 후  bytes Property 사용불가.

### ISSUE THREAD

**Issue by xowjd913** [naverz/zepeto-script-sample#77]
안녕하세요 불철주야 고생이 많으실꺼라봅니다.

Resources.Load로 TextAsset을 활용해 파일을 하나 읽어왔는데...

bytes Property를 사용하려고 보니 내부 값이 undefinded로 나옵니다.

파일이 바이너리 파일이긴 합니다...

다른 로드하는 방식이 있을까여 ? 아니면 바이너리 로드할 수 있게 해주세여

**Comment by hyeonjin-jo** [comment]
안녕하세요

답변이 늦어서 죄송합니다

해당 함수는 World package 1.1.2 이후 버전 부터 해결이 될 예정입니다

업데이트가 되면 아래 링크에서 공유하고 있습니다.
https://github.com/naverz/zepeto-studio-kor/discussions

업데이트된 릴리즈 정보는 아래의 릴리즈노트 링크에서 확인 부탁드립니다.
https://studio.zepeto.me/guides/world-release-note

감사합니다.
