### ISSUE TITLE
The ts file can't debugging in vscode,breakpoint is unbound but I can take the logs in output

### ISSUE THREAD

**Issue by Nowpaper** [naverz/zepeto-script-sample#80]
Follow this tutorial to debug，but the .ts file can't debugging in vscode
https://studio.zepeto.me/guides/debugging

but ... I can use 'chrome://inspect' debugging in Chrome Devtools for .js files
Puerts says that higher versions of vscode cannot be debugged, and it still cannot be debugged after trying to downgrade

**Comment by NoahHahm** [comment]
why should I use Chrome Devtools?
debugging is supported in the latest version of VSCode.

**Comment by Nowpaper** [comment]
I don't know why can't debugging in vscode , the breakpoint is gray when it's running, if project play in Unity Editor after run debugging
if run debugging before play project then vscode debugging will be stop

**Comment by Nowpaper** [comment]
https://github.com/Tencent/puerts/blob/master/doc/faq.md
It mentions that versions after 1.60 cannot be debug，I tried to set it like this but it still didn't work

**Comment by Nowpaper** [comment]
![Snipaste_2021-11-23_02-21-10](https://user-images.githubusercontent.com/2315547/142914955-ca073636-291c-4230-a926-b8fec6031d8e.jpg)

[vscode-debugadapter-4f06ae6f.json.gz](https://github.com/naverz/zepeto-script-sample/files/7583470/vscode-debugadapter-4f06ae6f.json.gz)
I upload log file to this issue , you can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains.

**Comment by x4cf** [comment]
new sample!
https://github.com/naverz/zepeto-multiplay-example

your project, in windows, not working properly, maybe

**Comment by x4cf** [comment]
now or today?, BreakingPoint, not working well

**Comment by NoahHahm** [comment]
<img width="1280" alt="capture" src="https://user-images.githubusercontent.com/6405162/142971613-a23a1bc9-0de6-4a09-b9ba-f80bf87512d9.PNG">
[vscode.zip](https://github.com/naverz/zepeto-script-sample/files/7585823/vscode.zip)

attach information and photos of the .vscode editor that is created in the project.
tested on windows 10.

**Comment by NoahHahm** [comment]
I have identified the problem in the sample project.

**Comment by Nowpaper** [comment]
> now or today?, BreakingPoint, not working well
> 
> *I am not official developer

No,I still can't work it

**Comment by Nowpaper** [comment]
> [vscode.zip](https://github.com/naverz/zepeto-script-sample/files/7585823/vscode.zip)
> 
> attach information and photos of the .vscode editor that is created in the project. tested on windows 10.
My project's setting is same for you ,and vscode version is 1.62.3
this screenshot shows the version and breakpoints. that debugger attach is display in the unity log panel ,but breakpoint is gray and not working

![Snipaste_2021-11-23_17-52-13](https://user-images.githubusercontent.com/2315547/143003156-ea88d5f1-f466-42fc-b67e-cda1c67e9452.jpg)

**Comment by NoahHahm** [comment]
we fixed the bug. we will be releasing a hotfix soon.
please wait.

**Comment by NoahHahm** [comment]
https://github.com/naverz/zepeto-script-sample/commit/81394b62c55104a99a9eed0163eb3d8d7afaae37

we fixed the issue. check it

**Comment by Nowpaper** [comment]
> [81394b6](https://github.com/naverz/zepeto-script-sample/commit/81394b62c55104a99a9eed0163eb3d8d7afaae37)
> 
> we fixed the issue. check it

Good job! It's woriking now.
I want to know why , because I have the same problem when using Puerts

**Comment by NoahHahm** [comment]
> 

all internal architecture has been changed based on Puerts.
So there may be differences.
