### ISSUE TITLE
unityevent 관련 질문입니다.

### ISSUE THREAD

**Issue by nx3-hds** [naverz/zepeto-script-sample#81]
https://studio.zepeto.me/guides/events

해당 가이드를 보면 AddListener 항목만 존재하고 있습니다.

그리고 안내에 따라 추가 정보를 가면 Unity 문서로 연결되어 있구요.
그런 상황에서 문서에 따라

Inherited members

![image](https://user-images.githubusercontent.com/94820939/142805683-34e4014f-88f5-4b57-b86e-c1e0e61d951e.png)

해당 항목이 지원 되는줄 알고 사용하였으나
 Cannot read property 'RemoveAllListeners' of null

property 를 읽을 수 없다고 나옵니다.

따라서 index.d 항목을 살펴보니

![image](https://user-images.githubusercontent.com/94820939/142806246-45032628-dcca-4e60-bf53-20f60abc641b.png)

항목에 없긴 합니다만 상위 base를 살펴 보니

![image](https://user-images.githubusercontent.com/94820939/142807078-ee2f56b4-979f-4ae3-b94c-c5bd319ce9e9.png)

존재하고 있습니다. typescript에서는 base에 접근하기 위해 super 키워드을 사용하였는데요. 저 메서드에 접근하기 위해서
super키워드의 사용 방법을 모르겠습니다.

다른 방법으로 접근해야 하는 것인지

Inherited members
항목을 지원하지 않는 것인지 
의도적으로 제외 하신건지
sdk에 누락이 된 기능인지 

알고 싶습니다.

누락이 되었다면 향후 버전에서 Listener 관련하여 대부분의 기능을 사용할 수 있는지 궁금합니다.

**Comment by crash-kim** [comment]
안녕하세요.
스펙 상 `UnityEventBase` 에 있는 메소드들은 접근이 가능합니다.
보내주신 Cannot read property 'RemoveAllListeners' of null 에러로 봤을 때 
null 인 객체의 `RemoveAllListeners` 를 접근하려고 하다 발생한 현상으로 보입니다.

`RemoveAllListeners`를 접근하려고 하는 객체가 null 인지 확인 부탁드립니다.

**Comment by hyeonjin-jo** [comment]
안녕하세요

추가 문의가 없어서 이슈 종료합니다. 해당 이슈가 재발하거나 해결되지 않은 상황이라면 reopen 부탁드립니다.
