### ISSUE TITLE
클라이언트 스토리지가 업데이트가 늦어지면 스키마에 인벤토리를 저장해도 될까요?

### ISSUE THREAD

**Issue by x4cf** [naverz/zepeto-script-sample#84]
업데이트나 서버가 꺼졌다 켜지면 다 날아가거나 하지는 않는걸까요? 12월 5일 심사넣고 빨리 유저들을 맞이하고 싶은데 가장 시급한 기능으로 보입니다. 스키마에 넣어도 안전하게 저장되나요?

**Comment by NoahHahm** [comment]
스키마에 넣는건 일시적 입니다.
따라서, 클라이언트 스토리지에 저장 해야하는데요.
해당 부분 빠르게 업데이트 될수있도록 내부에 전달하겠습니다.

**Comment by NoahHahm** [comment]
사용자의 영구적인 데이터 저장소는 서버 에서 DataStorage 를 통해 저장 하셔야 합니다.
클라이언트 스토리지 (PlayerPref) 는 앱삭제시 휘발성 데이터라는 점은 인지하셔야 합니다.

**Comment by x4cf** [comment]
아하! 답변감사합니다. 서버 데이터 스토리지 기능을 잊고있었네요! 👍
