### ISSUE TITLE
멀티플레이 채팅 / Breaking Point 관련 질문입니다.

### ISSUE THREAD

**Issue by xowjd913** [naverz/zepeto-script-sample#86]
1. 멸티플레이 월드 빌드 시 나오는 기본 디폴트 채팅창이있는데... 방에 접속한 유저가 작성한 채팅 내용을 가져올수 있는 방법이 있나요?
2. 자꾸 ZepetoScriptContext가 없어져서 중단점 찍고 디버깅이 안됩니다... 해결방법이 있나요?

**Comment by x4cf** [comment]
중단점 찍고 디버깅하는 기능은 현재 윈도우에서 정상작동하지 않는것같습니다.

**Comment by NoahHahm** [comment]
사용자 채팅 정보를 가지고 오는것은 지원되지 않고 있습니다.
사용자의 채팅 내용을 가져와야 하는 이유는 무엇입니까?

디버깅 이슈의 경우 #80 이슈와 겹치는 내용인것 같은데요.
정확한 환경과 재현경로를 첨부해주실수 있을까요?

**Comment by xowjd913** [comment]
> 

 - 채팅내용을 가져와야 하는 이유
    - 방에 참여 중인 누군가가 매핑 되어 있는 단어를 입력하면 오브젝트의 움직임이나 씬을 바꾸거나 하려고 합니다.

 - 디버깅 이슈 재현 경로 및 정확한 환경
 - Unity 2020.3.9 f1 Pro
 - PC 환경
     - WIndows 10 Pro 21H1
     - Intel i9-11900
     - 32G RAM
 - 재현경로 라고 표한하기 애매한게 Zepeto Default Project 로 프로젝트 만들고 두어번 빌드하면 ZepetoScriptContext 컴포넌트가 없어집니다.

**Comment by NoahHahm** [comment]
일종의 커스텀 커맨드를 작성하고자 의도하는게 맞을까요? (ex. /teleport)
디버깅 환경은 이슈 확인했습니다. 내부에서 확인 하고 추후 공유 드리겠습니다

**Comment by xowjd913** [comment]
> 

예를들어 방에있는 누군가 "축하해" 라는 채팅을 치면 월드에 세팅해놓은 동상의 춤추는 애니메이션을 플레이 하려는게 목표입니다

**Comment by NoahHahm** [comment]
디버깅 이슈는 1.0.4 핫픽스 릴리즈 되었으니
확인 부탁드립니다

**Comment by xowjd913** [comment]
> 디버깅 이슈는 1.0.4 핫픽스 릴리즈 되었으니 확인 부탁드립니다 단 채팅은 아직 적용예정이 없다보니 내부에 전달하겠습니다.

답변늦어서 죄송합니다. 디버깅은 현재 정상적으로 잘 동작합니다 감사합니다 :)
