### ISSUE TITLE
월드 내보내기 질문

### ISSUE THREAD

**Issue by egroy** [naverz/zepeto-script-sample#88]
안녕하세요. 

팀 내에서 '월드의 지형이나 가구 오브젝트 리소스들을 빌드잇에서 만들어서, 유니티로 가져와서 다듬으면 어떨까?'라는 의견이 있었는데요.  

![image](https://user-images.githubusercontent.com/18432755/142992366-c58708d3-874d-43ac-9720-65afe4e359e0.png)

보니깐 다른 확장자로 내보내기를 하는 기능은 없더라구요. ㅜㅜ

혹시 그런 기능이 가능한지 여쭈어 봅니다.

(구글에 관련 내용은 검색이 잘..) 

감사합니다!

**Comment by x4cf** [comment]
지원하지 않는 기능으로 알고있습니다, 페키지 메니저에서 빌드 오브젝트를 다운로드 할 수 있습니다. 유니티 안에서 빌드의 오브젝트를 이용해서 디자인해보는건 어떨까요?
<img width="470" alt="페키지메니저" src="https://user-images.githubusercontent.com/90679926/143019351-4f7d5b7e-c82e-4e43-a39b-516f6f0798a3.png">

**Comment by egroy** [comment]
오우 감사합니다!!
