### ISSUE TITLE
서버 room 접속 제어

### ISSUE THREAD

**Issue by diddntjd99** [naverz/zepeto-script-sample#91]
일정 인원의 플레이어가 차서 게임을 시작하게되면 그 room에 더이상 입장하지 못하게 코드로 제어하는 방법이 있을까요?

**Comment by NoahHahm** [comment]
다음 릴리즈에 룸 lock, unlock 기능이 추가되어 배포 예정 입니다.

**Comment by diddntjd99** [comment]
@NoahHahm 
감사합니다. 업데이트 되면 사용 방법도 공지를 해주시나요?

**Comment by NoahHahm** [comment]
네 업데이트시 공지 예정 입니다.
