### ISSUE TITLE
게임 용량 제한 있을까요?

### ISSUE THREAD

**Issue by leehearin** [naverz/zepeto-script-sample#92]
혹시 게임 용량이 정해져 있는지 질문드립니다.!
감사합니다 :)

**Comment by x4cf** [comment]
가이드 어디서 봤는지는 기억은나지 않지만 용량제한이 있었던걸로 기억합니다.

**Comment by mental-crash** [comment]
https://studio.zepeto.me/kr/guides/registering-a-world-file 여기 참조하시면 좋을 것 같습니다.
