### ISSUE TITLE
멀티플레이의 룸 메세지 데이터 접근 방법

### ISSUE THREAD

**Issue by diddntjd99** [naverz/zepeto-script-sample#95]
안녕하세요,
broadcast함수를 사용하여 서버에서 전체 클라이언트로 보낸 메세지를
클라이언트에서 받은 메세지 타입을 확인해보면 object 타입이라 데이터에 접근하기가 어렵습니다.

받은 메세지를 number형으로 변환하고 싶은데 방법을 알 수 있을까요?

**Comment by x4cf** [comment]
너는 받은 메세지 타입이 문자열로 나오는데 혹시 코드를 볼 수 있을까요?

스크린샷이나 코드를 보면서 제가 도울 수 있을것 같습니다.
이곳에 오시면 실시간으로 질문하시고 빠른시간안에 답변받으실 수 있습니다.
코드 : Me793a2
https://open.kakao.com/o/gNaIjUKd

**Comment by NoahHahm** [comment]
현 버전에서는 string 으로 보내고, string 으로 받아서 캐스팅하거나 처리해야 합니다. (1.0.4 기준)
다음 버전에서는 primitiveType, referenceType 을 지원할 예정 입니다.
ex.  AddMessageHandler 및 SendMessage / 클라 <-> 서버 간 메시지를 전송 타입으로 그대로 접근 가능하도록
