### ISSUE TITLE
외부통신을 해도 되나요?

### ISSUE THREAD

**Issue by x4cf** [naverz/zepeto-script-sample#96]
ZEPETO.Multiplay.HTTPService 를 이용한 외부 통신을 이용해도 되나요?

**Comment by NoahHahm** [comment]
서버에서 http 서비스를 제공하는 이유는 클라이언트에서 사용하기 민감한 정보를 외부에서 얻어오기 위함 입니다.
현 상황에서는 특별한 정책은 없어 사용하셔도 무방 합니다.

ex. 본인이 구축한 api 서버를 연동해서 토큰으로 연계하여 데이터를 주고받는 행위
      본인이 구축한 api 서버를 통해 데이터를 외부에 저장하는 행위

아직 정책이 없어 http 프로토콜도 지원하지만, 향후 보안정책상 http 통신은 불가능 할 수 있습니다. (샌드박스 개발 환경 제외)
혹은 허용된 도메인에 한해서만 통신을 지원할수도 있는 부분이기에 이부분은 감안하고 사용하셔야 합니다.
(샌드박스에서는 돌아가는데 리얼서버에서는 에러가 날수 있습니다.)

**Comment by x4cf** [comment]
https://studio.zepeto.me/guides/world-guidelines
2.5.5 가이드 규정과 상충되는것같습니다.
