### ISSUE TITLE
외부 앱 올려주는 링크 사용 

### ISSUE THREAD

**Issue by xowjd913** [naverz/zepeto-script-sample#97]
하이퍼링크를 주고 플레이스토어 화면이 나오도록 할 수 있나요 ?
현재 OpenUrl 메소드로 해당 방법을 진행해보려 했으나 에러가 나서 동작하지 않는 상황입니다.

**Comment by mhkim0720** [comment]
저도 답변 기다립니다. 되게 해주세요 제발 ㅋㅋ

**Comment by hyeonjin-jo** [comment]
안녕하세요

정책상 url은 허용하지 않고 있습니다

제페토 스튜디오 가이드라인 4-6을 참고 부탁드립니다.

https://studio.zepeto.me/kr/guides/common-guidelines
