### ISSUE TITLE
트리거이벤트 예제 에러 문의 

### ISSUE THREAD

**Issue by mhkim0720** [naverz/zepeto-script-sample#98]
https://studio.zepeto.me/guides/eventtrigger 요 페이지에 

            trigger.triggers.Add(entry); 이부분 add 함수가 없다고 뜨는데 해결방법이 뭘까요?

**Comment by crash-kim** [comment]
안녕하세요.
공유 해 드린 [index.d.ts](https://github.com/naverz/zepeto-script-sample/files/7622675/index.d.ts.zip) 파일을 Assets 폴더에 넣어주시면 해결이 될 것 같습니다.

이 이슈는 다음 버전에서 처리가 됩니다.(zepeto.world 1.0.5)

**Comment by mhkim0720** [comment]
현재 Assets /World.multiplay/ index.d.ts 가 있는데 이걸 Assets 아래로 옮기라는 거죠?

**Comment by crash-kim** [comment]
아닙니다. 
`Assets` 경로 안 다른 `index.d.ts`와 겹치지 않는 임의의 경로에 위에서 다운로드 받으신 `index.d.ts` 파일을 추가해 주시면 됩니다.

**Comment by hyeonjin-jo** [comment]
안녕하세요

답변이 늦어서 죄송합니다.

아래의 링크의 파일을  Assets /World.multiplay/ 경로를 제외하고   index.d.ts파일이 없는 경로에 추가 후 진행부탁드립니다.

https://github.com/naverz/zepeto-script-sample/blob/main/Assets/1.%20Basic/7.%20EventTrigger/index.d.ts
