### ISSUE TITLE
삼성 galaxy house 월드에 보면 클릭했을때 외부 웹 링크가 열리는 게 있는데 저런건 어떻게 하는지 궁금합니다. 

### ISSUE THREAD

**Issue by mhkim0720** [naverz/zepeto-script-sample#99]
유니티 OpenURL 외에 다른 함수로 구현한건가요? 
보니까 맵이름이 galaxy house 이고 공식맵이라고 되어잇네요 네이버 맵도 웹뷰 형식으로 열리는게 잇네요 이런 기능은 타입스크립트 개발환경에서는 구현이 불가능 한건가요?? 삼성맵은 되는데 왜 구현 불가 인지 설명이 필요한 상황이라 오피셜한 답변 부탁드립니다

**Comment by x4cf** [comment]
https://studio.zepeto.me/guides/world-guidelines
월드 가이드 링크 보내드립니다
월드 가이드 2.5.5 특정 액션 또는 이벤트로 외부 링크에 연결을 시도할 경우 승인 불가
